Job launching after 0.15 seconds in submission.
Running python job.
Changed into dir /home/masters/joe/deep-motion-analysis/gait_classification/joe_keras_work/experiments/2_LSTM
Importing 2LSTM-sm.py
Using Theano backend.
Using gpu device 0: GeForce GTX TITAN (CNMeM is disabled, cuDNN 5004)
Running 2LSTM-sm.main()
Traceback (most recent call last):
  File "/home/masters/jonathan/Spearmint/spearmint/launcher.py", line 243, in launch
    result = python_launcher(job)
  File "/home/masters/jonathan/Spearmint/spearmint/launcher.py", line 327, in python_launcher
    result = module.main(job['id'], params)
  File "/home/masters/joe/deep-motion-analysis/gait_classification/joe_keras_work/experiments/2_LSTM/2LSTM-sm.py", line 77, in main
    return model(params)
  File "/home/masters/joe/deep-motion-analysis/gait_classification/joe_keras_work/experiments/2_LSTM/2LSTM-sm.py", line 30, in model
    data = np.load('$HOME/joe/deep-motion-analysis/gait_classification/data/Joe/sequential_final_frame.npz')
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '$HOME/joe/deep-motion-analysis/gait_classification/data/Joe/sequential_final_frame.npz'
Problem executing the function
Job failed in 9.10 seconds.
Anything printed here will end up in the output directory for job #6
(<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x7f70104c7998>)
